[package]
name = "pokescheme"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
color-thief = "0.2"
image = "0.25.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0"
homedir = "0.3.3"
wallpaper = "3.2.0"
